Feature/jeux essais
hackathoncovid19/aidonslesaidants pull request #10
Opened 2020-03-21 16:35 UTC by forsanta

Afin de pouvoir tester l'application
je souhaite avoir un jeux de test de données
en tant que développeur

2020-03-21 18:45 UTC, Emma1987 commented on insert-data.sql
> +INSERT INTO user (id,username,password,roles) VALUES (1,"muriel.user","ad167fa654f27bb3707f76cf506508f6","user");
Juste une info, les rôles doivent être préfixé par ROLE_

2020-03-21 18:45 UTC, nbensalha commented on insert-data.sql
> +INSERT INTO user (id,username,password,roles) VALUES (1,"muriel.user","ad167fa654f27bb3707f76cf506508f6","user");
Les roles sont des JSON array du coup ils doivent ressembler à ça : 

`a:1:{i:0;s:9:"ROLE_USER";}`

2020-03-21 18:46 UTC, BusyChild77 requested changes
Les roles sont à changer de format, hormis ça c'est top ! On va pouvoir avoir de quoi tester :)

2020-03-21 20:00 UTC, Emma1987 commented on insert-data.sql
> +INSERT INTO user (id,username,password,roles) VALUES (1,"muriel.user","ad167fa654f27bb3707f76cf506508f6","user");
Merci 🙏 C'est exactement l'info que je cherchais

2020-03-21 20:53 UTC, forsanta commented on insert-data.sql
> +INSERT INTO user (id,username,password,roles) VALUES (1,"muriel.user","ad167fa654f27bb3707f76cf506508f6","user");
j'ai mit a jour le script

2020-03-22 00:15 UTC, nbensalha commented on insert-data.sql
> +INSERT INTO user (id,username,password,roles) VALUES (1,"muriel.user","ad167fa654f27bb3707f76cf506508f6","user");
C'est presque bon, il faudrait juste remplacer les `a:1:{i:0;s:9:'ROLE_ADMIN';}` par a:1:`{i:0;s:10:'ROLE_ADMIN';}` (`s` étant la longueur de la chaîne de caractères du ROLE, ça plante)

2020-03-22 00:20 UTC, nbensalha commented on insert-data.sql
> +INSERT INTO user (id,username,password,roles) VALUES (1,"muriel.user","ad167fa654f27bb3707f76cf506508f6","user");
Autre chose, ce serait pas mal d'avoir des `TRUNCATE TABLE ticket `et `TRUNCATE TABLE user` avant les inserts histoire de vider les tables

2020-03-22 09:09 UTC, forsanta commented on insert-data.sql
> +INSERT INTO user (id,username,password,roles) VALUES (1,"muriel.user","ad167fa654f27bb3707f76cf506508f6","user");
ha ok , je modifie ca

2020-03-22 12:53 UTC, BusyChild77 approved these changes

2020-03-22 12:56 UTC, merged