tel & mail on contact
hackathoncovid19/aidonslesaidants pull request #55
Opened 2020-03-25 21:13 UTC by kromajmun

2020-03-27 10:21 UTC, iGitScor requested changes

2020-03-27 10:21 UTC, iGitScor commented on templates/ticket/view.html.twig
> +                            {% if ticket.contact matches "#^([-/+,;. ]?[0-9]{1}){6,12}$#" %}
```suggestion
                            {% if ticket.contact matches "/^([-/+,;. ]?[0-9]{1}){6,12}$/" %}
```

Par contre je comprends pas pourquoi accepter `-/,;. `

2020-03-27 13:45 UTC, kromajmun commented
> Le mieux c'est de sortir ça. Et d'en faire un service puis une extension twig qui appellerait ce service

Je saurais pas faire :/

2020-03-28 02:41 UTC, kromajmun commented
@ntchou @iGitScor du coup on laisse tomber ou on passe et on fera un refacto plus tard ?

2020-03-28 16:16 UTC, ntchou commented
On peut tjrs le faire passer si c'est prioritaire. Et revenir dessus après. On a une tâche refacto

2020-03-28 17:19 UTC, merged