Feature/contacter un administrateur
hackathoncovid19/aidonslesaidants pull request #6
Opened 2020-03-21 12:34 UTC by forsanta

https://trello.com/c/RGZ4DLiq/7-bo-contacter-un-administrateur

Afin de pouvoir notifier l'équipe technique d'éventuels évolutions ou bug
je souhaite avoir un mail de contact de l'équipe technique
en tant que proche d'un soignant

Ajout d'un fichier footer.html.twig

2020-03-21 12:44 UTC, BusyChild77 requested changes

2020-03-21 12:44 UTC, nbensalha commented on .gitignore
> +.docker/docker-compose.yml
Il faut garder le docker-compose dans la conf, cependant effectivement il faudrait changer le port HTML vers quelque chose de moins conflictuel avec d'autres projets (9090 ou autre)

2020-03-21 12:44 UTC, nbensalha commented on templates/base.html.twig
> +        <title>{% block title %}bienvenu!{% endblock %}</title>
Il faudra valider le wording avec Remi et Seb, je ne sais pas si quelque chose a déjà été fait à ce niveau

Aussi, il faudra installer le module de traduction de twig et utiliser la fonction 'trans'

2020-03-21 12:49 UTC, forsanta commented on .gitignore
> +.docker/docker-compose.yml
j'ai fait un raz

2020-03-21 12:49 UTC, forsanta commented on templates/base.html.twig
> +        <title>{% block title %}bienvenu!{% endblock %}</title>
idem raz

2020-03-21 14:33 UTC, iGitScor commented on templates/footer.html.twig
> +<a href="alaid.tech@gmail.com>Contact</a>
```suggestion
<a href="mailto:alaid.tech@gmail.com">Contact</a>
```

2020-03-23 13:17 UTC, ntchou commented
On peut close cette mr. Ces modifs sont déjà dans develop

2020-03-23 13:17 UTC, closed without merging