[BO] En tant que proche du soignant, je peux m'inscrire au back-office
hackathoncovid19/aidonslesaidants pull request #8
Opened 2020-03-21 14:22 UTC by mauradelrosario

2020-03-21 18:48 UTC, nbensalha commented on src/Controller/UserController.php
> +    public function createAction()
pas besoin de suffixer avec "Action" dans les dernières versions de SF

2020-03-22 00:58 UTC, BusyChild77 requested changes

2020-03-22 00:58 UTC, BusyChild77 commented on config/routes.yaml
> +user_new_create:
Pas besoin de spécifier la route car elle est déjà crée via l'annotation :
`@Route("/new", name="edit", methods={"GET","POST"})
`

au dessus de la fonction dans le controller

2020-03-23 11:44 UTC, BusyChild77 approved these changes

2020-03-24 15:38 UTC, iGitScor approved these changes

2020-03-24 16:11 UTC, merged